# Generated by Django 5.2.4 on 2025-07-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('long_description', models.TextField(verbose_name='Описание')),
                ('coordinates_lng', models.FloatField(verbose_name='Долгота')),
                ('coordinates_lat', models.FloatField(verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('url', models.URLField(null=True, verbose_name='URL изображения')),
                ('ordinal_number', models.IntegerField(unique=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.organizers')),
            ],
        ),
    ]
