# Generated by Django 5.2.4 on 2025-07-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('long_description', models.TextField(verbose_name='Описание')),
                ('coordinates_lng', models.FloatField(verbose_name='Долгота')),
                ('coordinates_lat', models.FloatField(verbose_name='Широта')),
            ],
        ),
    ]
