# Generated by Django 5.2.4 on 2025-07-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
