# Generated by Django 5.2.4 on 2025-07-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
