# Generated by Django 5.2.4 on 2025-07-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_places_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Organizers',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.organizers')),
            ],
        ),
    ]
