# Generated by Django 5.2.4 on 2025-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_places_organizers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizers',
            name='short_description',
            field=models.CharField(max_length=500, verbose_name='Краткое описание'),
        ),
    ]
