# Generated by Django 5.2.4 on 2025-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_image_ordinal_number_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
    ]
