# Generated by Django 5.2.4 on 2025-07-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_organizers_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='image',
        ),
    ]
