# Generated by Django 5.2.4 on 2025-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-ordinal_number']},
        ),
        migrations.AddField(
            model_name='image',
            name='ordinal_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
