# Generated by Django 5.2.4 on 2025-08-04 07:31

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options_image_ordinal_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='long_description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
