# Generated by Django 5.2.4 on 2025-08-04 07:36

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_image_url_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizers',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
    ]
