# Generated by Django 5.2.4 on 2025-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_organizers_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizers',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
