# Generated by Django 5.2.4 on 2025-08-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_organizers_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal_number',
            field=models.PositiveIntegerField(verbose_name='Номер по порядку'),
        ),
        migrations.AlterField(
            model_name='image',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.organizers', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['organizer', 'ordinal_number'], name='places_imag_organiz_095758_idx'),
        ),
    ]
