# Generated by Django 5.2.4 on 2025-08-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_ordinal_number_alter_image_organizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal_number',
            field=models.PositiveIntegerField(blank=True, verbose_name='Номер по порядку'),
        ),
    ]
