# Generated by Django 5.2.4 on 2025-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_ordinal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal_number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер по порядку'),
        ),
    ]
