# Generated by Django 5.2.4 on 2025-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_ordinal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizers',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
